//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversionServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference.IConversionUnidadesServicio")]
    public interface IConversionUnidadesServicio
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadasResponse")]
        System.Threading.Tasks.Task<double> CentimetrosAPulgadasAsync(double centimetros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IConversionUnidadesServicioChannel : ConversionServiceReference.IConversionUnidadesServicio, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ConversionUnidadesServicioClient : System.ServiceModel.ClientBase<ConversionServiceReference.IConversionUnidadesServicio>, ConversionServiceReference.IConversionUnidadesServicio
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConversionUnidadesServicioClient() : 
                base(ConversionUnidadesServicioClient.GetDefaultBinding(), ConversionUnidadesServicioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConversionUnidadesServicio.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionUnidadesServicioClient(EndpointConfiguration endpointConfiguration) : 
                base(ConversionUnidadesServicioClient.GetBindingForEndpoint(endpointConfiguration), ConversionUnidadesServicioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionUnidadesServicioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConversionUnidadesServicioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionUnidadesServicioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConversionUnidadesServicioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionUnidadesServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double pulgadas)
        {
            return base.Channel.PulgadasACentimetrosAsync(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> CentimetrosAPulgadasAsync(double centimetros)
        {
            return base.Channel.CentimetrosAPulgadasAsync(centimetros);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionUnidadesServicio))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionUnidadesServicio))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.254.76:8733/Design_Time_Addresses/CONUNIL_GR05/ConversionUnidadesS" +
                        "ervicio/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConversionUnidadesServicioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConversionUnidadesServicio);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConversionUnidadesServicioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConversionUnidadesServicio);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConversionUnidadesServicio,
        }
    }
}
