//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLICLON_CONUNI_GR05.ConversionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference.IConversionUnidadesServicio")]
    public interface IConversionUnidadesServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetrosResponse")]
        double PulgadasACentimetros(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/PulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadasResponse")]
        double CentimetrosAPulgadas(double centimetros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadas", ReplyAction="http://tempuri.org/IConversionUnidadesServicio/CentimetrosAPulgadasResponse")]
        System.Threading.Tasks.Task<double> CentimetrosAPulgadasAsync(double centimetros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionUnidadesServicioChannel : CLICLON_CONUNI_GR05.ConversionServiceReference.IConversionUnidadesServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionUnidadesServicioClient : System.ServiceModel.ClientBase<CLICLON_CONUNI_GR05.ConversionServiceReference.IConversionUnidadesServicio>, CLICLON_CONUNI_GR05.ConversionServiceReference.IConversionUnidadesServicio {
        
        public ConversionUnidadesServicioClient() {
        }
        
        public ConversionUnidadesServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionUnidadesServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionUnidadesServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionUnidadesServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double PulgadasACentimetros(double pulgadas) {
            return base.Channel.PulgadasACentimetros(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> PulgadasACentimetrosAsync(double pulgadas) {
            return base.Channel.PulgadasACentimetrosAsync(pulgadas);
        }
        
        public double CentimetrosAPulgadas(double centimetros) {
            return base.Channel.CentimetrosAPulgadas(centimetros);
        }
        
        public System.Threading.Tasks.Task<double> CentimetrosAPulgadasAsync(double centimetros) {
            return base.Channel.CentimetrosAPulgadasAsync(centimetros);
        }
    }
}
