package ec.edu.monster.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-17T12:15:27.619-05:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "WSConUni",
                  wsdlLocation = "http://localhost:8080/WS_ConUni_SOAPJAVA_GR08/WSConUni?wsdl",
                  targetNamespace = "http://ws.monster.edu.ec/")
public class WSConUni_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.monster.edu.ec/", "WSConUni");
    public final static QName WSConUniPort = new QName("http://ws.monster.edu.ec/", "WSConUniPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WS_ConUni_SOAPJAVA_GR08/WSConUni?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSConUni_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/WS_ConUni_SOAPJAVA_GR08/WSConUni?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSConUni_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSConUni_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSConUni_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSConUni_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSConUni_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSConUni_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSConUni
     */
    @WebEndpoint(name = "WSConUniPort")
    public WSConUni getWSConUniPort() {
        return super.getPort(WSConUniPort, WSConUni.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSConUni
     */
    @WebEndpoint(name = "WSConUniPort")
    public WSConUni getWSConUniPort(WebServiceFeature... features) {
        return super.getPort(WSConUniPort, WSConUni.class, features);
    }

}
