package ec.edu.monster.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-17T12:15:27.558-05:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://ws.monster.edu.ec/", name = "WSConUni")
@XmlSeeAlso({ObjectFactory.class})
public interface WSConUni {

    @WebMethod
    @Action(input = "http://ws.monster.edu.ec/WSConUni/kelvinACelsiusRequest", output = "http://ws.monster.edu.ec/WSConUni/kelvinACelsiusResponse")
    @RequestWrapper(localName = "kelvinACelsius", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.KelvinACelsius")
    @ResponseWrapper(localName = "kelvinACelsiusResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.KelvinACelsiusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double kelvinACelsius(

        @WebParam(name = "kelvin", targetNamespace = "")
        double kelvin
    );

    @WebMethod
    @Action(input = "http://ws.monster.edu.ec/WSConUni/kilogramosAGramosRequest", output = "http://ws.monster.edu.ec/WSConUni/kilogramosAGramosResponse")
    @RequestWrapper(localName = "kilogramosAGramos", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.KilogramosAGramos")
    @ResponseWrapper(localName = "kilogramosAGramosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.KilogramosAGramosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double kilogramosAGramos(

        @WebParam(name = "kilogramos", targetNamespace = "")
        double kilogramos
    );

    @WebMethod
    @Action(input = "http://ws.monster.edu.ec/WSConUni/celsiusAKelvinRequest", output = "http://ws.monster.edu.ec/WSConUni/celsiusAKelvinResponse")
    @RequestWrapper(localName = "celsiusAKelvin", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.CelsiusAKelvin")
    @ResponseWrapper(localName = "celsiusAKelvinResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.CelsiusAKelvinResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double celsiusAKelvin(

        @WebParam(name = "celsius", targetNamespace = "")
        double celsius
    );

    @WebMethod
    @Action(input = "http://ws.monster.edu.ec/WSConUni/pulgadasACentimetrosRequest", output = "http://ws.monster.edu.ec/WSConUni/pulgadasACentimetrosResponse")
    @RequestWrapper(localName = "pulgadasACentimetros", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.PulgadasACentimetros")
    @ResponseWrapper(localName = "pulgadasACentimetrosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.PulgadasACentimetrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double pulgadasACentimetros(

        @WebParam(name = "pulgadas", targetNamespace = "")
        double pulgadas
    );

    @WebMethod
    @Action(input = "http://ws.monster.edu.ec/WSConUni/gramosAKilogramosRequest", output = "http://ws.monster.edu.ec/WSConUni/gramosAKilogramosResponse")
    @RequestWrapper(localName = "gramosAKilogramos", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.GramosAKilogramos")
    @ResponseWrapper(localName = "gramosAKilogramosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.GramosAKilogramosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double gramosAKilogramos(

        @WebParam(name = "gramos", targetNamespace = "")
        double gramos
    );

    @WebMethod
    @Action(input = "http://ws.monster.edu.ec/WSConUni/centimetrosAPulgadasRequest", output = "http://ws.monster.edu.ec/WSConUni/centimetrosAPulgadasResponse")
    @RequestWrapper(localName = "centimetrosAPulgadas", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.CentimetrosAPulgadas")
    @ResponseWrapper(localName = "centimetrosAPulgadasResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.CentimetrosAPulgadasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double centimetrosAPulgadas(

        @WebParam(name = "centimetros", targetNamespace = "")
        double centimetros
    );
}
