package ec.edu.monster.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-17T17:10:22.319-05:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://servicio.monster.edu.ec/", name = "LoginService")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginService {

    @WebMethod
    @Action(input = "http://servicio.monster.edu.ec/LoginService/loginRequest", output = "http://servicio.monster.edu.ec/LoginService/loginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://servicio.monster.edu.ec/", className = "ec.edu.monster.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://servicio.monster.edu.ec/", className = "ec.edu.monster.ws.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean login(

        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
