package ec.edu.monster.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-10-17T17:10:22.325-05:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "Login",
                  wsdlLocation = "http://localhost:8080/WS_ConUni_SOAPJAVA_GR08/Login?wsdl",
                  targetNamespace = "http://servicio.monster.edu.ec/")
public class Login_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicio.monster.edu.ec/", "Login");
    public final static QName LoginServicePort = new QName("http://servicio.monster.edu.ec/", "LoginServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WS_ConUni_SOAPJAVA_GR08/Login?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Login_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/WS_ConUni_SOAPJAVA_GR08/Login?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Login_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Login_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Login_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Login_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Login_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Login_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServicePort")
    public LoginService getLoginServicePort() {
        return super.getPort(LoginServicePort, LoginService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServicePort")
    public LoginService getLoginServicePort(WebServiceFeature... features) {
        return super.getPort(LoginServicePort, LoginService.class, features);
    }

}
